import React, { useState } from 'react';

// Deterministic hash function
const stringToHash = (str: string): number => {
    let hash = 0;
    if (str.length === 0) return hash;
    for (let i = 0; i < str.length; i++) {
        const char = str.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash |= 0; // Convert to 32bit integer
    }
    return Math.abs(hash);
};

const jobPrefixes = [
    'Quantum', 'Bio-Synth', 'Cybernetic', 'Holo-', 'Neuro-', 'Astro-', 'Eco-', 'Chrono-', 'Data-', 'Dream-'
];
const jobSuffixes = [
    'Weaver', 'Sculptor', 'Guardian', 'Navigator', 'Architect', 'Harmonizer', 'Tinkerer', 'Analyst', 'Whisperer', 'Pioneer'
];
const jobDescriptions = [
    'You manipulate quantum foam to build next-generation reality simulations.',
    'You design and cultivate synthetic organisms for terraforming distant planets.',
    'You maintain and upgrade the neural interfaces that connect humanity to the global net.',
    'You craft interactive holographic experiences for entertainment and education.',
    'You map and interpret the complex neural pathways of artificial intelligences.',
    'You chart courses through newly discovered wormholes for interstellar colonization.',
    'You restore and manage Earth\'s delicate ecosystems using advanced nano-robotics.',
    'You ensure the integrity of the timeline by correcting paradoxes and temporal anomalies.',
    'You find meaningful patterns in the exabytes of data generated by the solar system.',
    'You venture into the shared subconscious to resolve psychological conflicts and inspire creativity.'
];


export const AiFutureJobFinder: React.FC = () => {
    const [name, setName] = useState('');
    const [hobby, setHobby] = useState('');
    const [result, setResult] = useState<{ title: string; description: string } | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    const predictFuture = () => {
        if (!name.trim() || !hobby.trim()) return;

        setIsLoading(true);
        setResult(null);

        setTimeout(() => {
            const combinedInput = `${name.toLowerCase().trim()}-${hobby.toLowerCase().trim()}`;
            const hash = stringToHash(combinedInput);
            
            const prefix = jobPrefixes[hash % jobPrefixes.length];
            const suffix = jobSuffixes[hash % jobSuffixes.length];
            const description = jobDescriptions[hash % jobDescriptions.length];

            setResult({
                title: `${prefix}${suffix}`,
                description: description
            });
            setIsLoading(false);
        }, 2000); // Simulate AI thinking time
    };
    
    return (
        <div className="max-w-2xl mx-auto text-center p-8 bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700">
             <div className="text-center mb-8">
                <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white">AI Future Job Finder 🚀</h1>
                <p className="text-slate-500 dark:text-slate-400 mt-2 text-lg">Tell us about yourself and we'll predict your career in the 22nd century!</p>
            </div>
            
            <div className="space-y-6">
                 <div>
                    <label htmlFor="your-name" className="block text-sm font-medium text-slate-700 dark:text-slate-300 text-left mb-1">Your Name</label>
                    <input
                        id="your-name"
                        type="text"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        placeholder="e.g., Casey"
                        className="w-full bg-white dark:bg-slate-900/50 border border-slate-300 dark:border-slate-600 rounded-lg p-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition"
                        aria-label="Your Name"
                    />
                </div>
                 <div>
                    <label htmlFor="your-hobby" className="block text-sm font-medium text-slate-700 dark:text-slate-300 text-left mb-1">Your Favorite Hobby</label>
                    <input
                        id="your-hobby"
                        type="text"
                        value={hobby}
                        onChange={(e) => setHobby(e.target.value)}
                        placeholder="e.g., Stargazing"
                        className="w-full bg-white dark:bg-slate-900/50 border border-slate-300 dark:border-slate-600 rounded-lg p-3 text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition"
                        aria-label="Your Favorite Hobby"
                    />
                </div>
            </div>
            
            <button
                onClick={predictFuture}
                disabled={isLoading || !name.trim() || !hobby.trim()}
                className="mt-8 w-full flex items-center justify-center px-6 py-4 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-lg shadow-lg transition-all duration-300 disabled:bg-slate-400 dark:disabled:bg-slate-600 disabled:cursor-not-allowed transform hover:scale-105"
            >
              {isLoading ? (
                <>
                  <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Scanning Future Timelines...
                </>
              ) : (
                'Predict My Future'
              )}
            </button>

            {result && !isLoading && (
                 <div className="mt-8 p-6 bg-slate-100 dark:bg-slate-900/50 rounded-lg border border-slate-200 dark:border-slate-700 animate-fade-in text-left">
                    <h3 className="text-sm font-semibold text-indigo-500 dark:text-indigo-400 uppercase tracking-wider">Your Future Career:</h3>
                    <p className="text-3xl font-bold text-slate-800 dark:text-slate-100 mt-1">{result.title}</p>
                    <p className="mt-3 text-slate-600 dark:text-slate-300">{result.description}</p>
                 </div>
            )}
             <style>
                {`
                @keyframes fade-in {
                    from { opacity: 0; transform: translateY(10px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                .animate-fade-in {
                    animation: fade-in 0.5s ease-out forwards;
                }
                `}
            </style>
        </div>
    );
};
